export const mockJobs = [
  {
    id: "1",
    title: "Back Office Executive",
    company: "Infosys BPO",
    companyLogo: "IB",
    location: "Bangalore, India",
    salary: "₹3.5L – ₹5L",
    type: "Full-time",
    remote: false,
    skills: ["MS Office", "Data Entry", "Communication"],
    description: "Manage day-to-day back office operations including data management, documentation, and reporting. Coordinate with internal teams for smooth workflow.",
    responsibilities: [
      "Process and manage internal documentation",
      "Maintain and update databases accurately",
      "Coordinate with teams for data accuracy",
      "Generate daily and weekly reports",
      "Handle email correspondence",
    ],
    posted: "2 hours ago",
    applicants: 42,
    matchScore: 95,
  },
  {
    id: "2",
    title: "Data Entry Operator",
    company: "TCS",
    companyLogo: "TC",
    location: "Pune, India",
    salary: "₹2.5L – ₹4L",
    type: "Full-time",
    remote: false,
    skills: ["Typing", "Excel", "Attention to Detail"],
    description: "Accurate and efficient data entry from various sources into our database systems. Verify data integrity and produce reports as needed.",
    responsibilities: [
      "Enter data from source documents into systems",
      "Verify data accuracy by comparing to source",
      "Update existing records in database",
      "Retrieve data as requested",
      "Maintain confidentiality of information",
    ],
    posted: "5 hours ago",
    applicants: 28,
    matchScore: 88,
  },
  {
    id: "3",
    title: "Data Analyst",
    company: "Wipro Analytics",
    companyLogo: "WA",
    location: "Hyderabad, India",
    salary: "₹6L – ₹10L",
    type: "Full-time",
    remote: true,
    skills: ["SQL", "Python", "Power BI"],
    description: "Analyze large datasets to derive meaningful business insights. Create dashboards and reports that drive decision-making across the organization.",
    responsibilities: [
      "Collect and clean data from multiple sources",
      "Build dashboards using Power BI / Tableau",
      "Write SQL queries for data extraction",
      "Present findings to stakeholders",
      "Identify trends and patterns in data",
    ],
    posted: "1 day ago",
    applicants: 67,
    matchScore: 72,
  },
  {
    id: "4",
    title: "HR Executive",
    company: "Reliance Industries",
    companyLogo: "RI",
    location: "Mumbai, India",
    salary: "₹4L – ₹7L",
    type: "Full-time",
    remote: false,
    skills: ["Recruitment", "HRMS", "Communication"],
    description: "Handle end-to-end recruitment, employee onboarding, and HR policy implementation. Support organizational development initiatives.",
    responsibilities: [
      "Manage end-to-end recruitment process",
      "Conduct employee onboarding programs",
      "Maintain employee records and HRMS",
      "Handle payroll queries",
      "Organize team engagement activities",
    ],
    posted: "3 days ago",
    applicants: 53,
    matchScore: 65,
  },
  {
    id: "5",
    title: "Office Assistant",
    company: "Mahindra Group",
    companyLogo: "MG",
    location: "Delhi, India",
    salary: "₹2L – ₹3.5L",
    type: "Full-time",
    remote: false,
    skills: ["Filing", "MS Office", "Coordination"],
    description: "Provide administrative support to the office team. Handle filing, scheduling, and day-to-day office operations.",
    responsibilities: [
      "Manage front desk operations",
      "Handle file management and documentation",
      "Schedule meetings and appointments",
      "Assist in inventory management",
      "Support other admin tasks as needed",
    ],
    posted: "1 week ago",
    applicants: 19,
    matchScore: 80,
  },
  {
    id: "6",
    title: "Customer Support Executive",
    company: "Flipkart",
    companyLogo: "FK",
    location: "Bangalore, India",
    salary: "₹3L – ₹5L",
    type: "Full-time",
    remote: true,
    skills: ["Communication", "CRM", "Problem Solving"],
    description: "Provide exceptional customer service via chat, email, and phone. Resolve customer queries and escalate issues when needed.",
    responsibilities: [
      "Handle customer queries via chat and email",
      "Resolve complaints within SLA timelines",
      "Update CRM with interaction details",
      "Escalate complex issues to supervisors",
      "Maintain high customer satisfaction scores",
    ],
    posted: "4 days ago",
    applicants: 35,
    matchScore: 76,
  },
  {
    id: "7",
    title: "Accountant",
    company: "Deloitte India",
    companyLogo: "DI",
    location: "Chennai, India",
    salary: "₹5L – ₹8L",
    type: "Full-time",
    remote: false,
    skills: ["Tally", "GST", "Accounting"],
    description: "Handle accounts payable/receivable, prepare financial statements, and ensure compliance with taxation regulations.",
    responsibilities: [
      "Prepare monthly financial statements",
      "Manage accounts payable and receivable",
      "Handle GST filings and tax compliance",
      "Perform bank reconciliations",
      "Assist in annual audit preparation",
    ],
    posted: "2 days ago",
    applicants: 24,
    matchScore: 70,
  },
  {
    id: "8",
    title: "Content Writer",
    company: "Zomato",
    companyLogo: "ZM",
    location: "Gurugram, India",
    salary: "₹3L – ₹5.5L",
    type: "Full-time",
    remote: true,
    skills: ["Writing", "SEO", "Research"],
    description: "Create engaging content for blogs, social media, and marketing campaigns. Research industry topics and produce high-quality copy.",
    responsibilities: [
      "Write blog posts and articles",
      "Create social media content",
      "Optimize content for SEO",
      "Collaborate with marketing team",
      "Proofread and edit content",
    ],
    posted: "6 hours ago",
    applicants: 41,
    matchScore: 82,
  },
];

export const mockApplications = [
  { id: "1", jobTitle: "Back Office Executive", company: "Infosys BPO", status: "interview", appliedDate: "2024-03-15", logo: "IB" },
  { id: "2", jobTitle: "Data Analyst", company: "Wipro Analytics", status: "shortlisted", appliedDate: "2024-03-12", logo: "WA" },
  { id: "3", jobTitle: "HR Executive", company: "Reliance Industries", status: "applied", appliedDate: "2024-03-10", logo: "RI" },
  { id: "4", jobTitle: "Customer Support Executive", company: "Flipkart", status: "hired", appliedDate: "2024-02-28", logo: "FK" },
];

export const mockCandidates = [
  { id: "1", name: "Rahul Sharma", role: "Data Entry Operator", experience: "3 years", skills: ["Excel", "Typing"], score: 95, status: "applied", avatar: "RS", email: "rahul@email.com", phone: "+91 98765 43210" },
  { id: "2", name: "Priya Gupta", role: "HR Executive", experience: "4 years", skills: ["Recruitment", "HRMS"], score: 88, status: "shortlisted", avatar: "PG", email: "priya@email.com", phone: "+91 98765 43211" },
  { id: "3", name: "Amit Patel", role: "Data Analyst", experience: "5 years", skills: ["SQL", "Python"], score: 92, status: "interview", avatar: "AP", email: "amit@email.com", phone: "+91 98765 43212" },
  { id: "4", name: "Sneha Reddy", role: "Content Writer", experience: "2 years", skills: ["Writing", "SEO"], score: 85, status: "hired", avatar: "SR", email: "sneha@email.com", phone: "+91 98765 43213" },
  { id: "5", name: "Vikram Singh", role: "Accountant", experience: "6 years", skills: ["Tally", "GST"], score: 78, status: "applied", avatar: "VS", email: "vikram@email.com", phone: "+91 98765 43214" },
  { id: "6", name: "Anjali Nair", role: "Office Assistant", experience: "2 years", skills: ["MS Office", "Filing"], score: 90, status: "shortlisted", avatar: "AN", email: "anjali@email.com", phone: "+91 98765 43215" },
];

export const mockCompanies = [
  { id: "1", name: "Infosys BPO", industry: "IT Services", employees: "1000+", approved: true, logo: "IB", jobs: 12 },
  { id: "2", name: "TCS", industry: "IT Services", employees: "5000+", approved: true, logo: "TC", jobs: 8 },
  { id: "3", name: "Wipro Analytics", industry: "Analytics", employees: "500+", approved: true, logo: "WA", jobs: 15 },
  { id: "4", name: "StartupHub", industry: "Fintech", employees: "10-50", approved: false, logo: "SH", jobs: 3 },
  { id: "5", name: "Reliance Industries", industry: "Conglomerate", employees: "10000+", approved: true, logo: "RI", jobs: 6 },
  { id: "6", name: "TechNova", industry: "Software", employees: "50-100", approved: false, logo: "TN", jobs: 4 },
  { id: "7", name: "GreenLeaf Solutions", industry: "EdTech", employees: "20-50", approved: false, logo: "GL", jobs: 2 },
];

export const mockAdminStats = {
  totalUsers: 12480,
  totalCompanies: 342,
  activeJobs: 1856,
  placements: 728,
  pendingApprovals: 14,
  flaggedJobs: 7,
};

export const mockActivityLog = [
  { id: "1", action: "New company registered", detail: "TechNova Inc.", time: "2 min ago", type: "info" as const },
  { id: "2", action: "Job flagged for review", detail: "Suspicious salary range", time: "15 min ago", type: "warning" as const },
  { id: "3", action: "Company approved", detail: "Reliance Industries", time: "1 hour ago", type: "success" as const },
  { id: "4", action: "User reported", detail: "Fake profile detected", time: "2 hours ago", type: "danger" as const },
  { id: "5", action: "New placement", detail: "Sneha Reddy → Flipkart", time: "3 hours ago", type: "success" as const },
];

export const mockUsers = [
  { id: "1", name: "Rahul Sharma", email: "rahul@email.com", role: "seeker", status: "active", joined: "2024-01-15", profileCompletion: 85 },
  { id: "2", name: "Priya Gupta", email: "priya@email.com", role: "seeker", status: "active", joined: "2024-02-20", profileCompletion: 92 },
  { id: "3", name: "Amit Patel", email: "amit@email.com", role: "seeker", status: "active", joined: "2024-01-08", profileCompletion: 78 },
  { id: "4", name: "Sneha Reddy", email: "sneha@email.com", role: "seeker", status: "suspended", joined: "2024-03-01", profileCompletion: 60 },
  { id: "5", name: "Vikram Singh", email: "vikram@email.com", role: "company", status: "active", joined: "2024-02-10", profileCompletion: 100 },
  { id: "6", name: "Anjali Nair", email: "anjali@email.com", role: "seeker", status: "active", joined: "2024-03-05", profileCompletion: 45 },
];

export const mockPlacements = [
  { id: "1", candidate: "Sneha Reddy", company: "Flipkart", role: "Customer Support Executive", salary: "₹4.5L", date: "2024-03-10", status: "confirmed" },
  { id: "2", candidate: "Amit Patel", company: "Wipro Analytics", role: "Data Analyst", salary: "₹8L", date: "2024-03-05", status: "confirmed" },
  { id: "3", candidate: "Rahul Sharma", company: "Infosys BPO", role: "Back Office Executive", salary: "₹4L", date: "2024-02-28", status: "pending" },
  { id: "4", candidate: "Priya Gupta", company: "Reliance Industries", role: "HR Executive", salary: "₹6L", date: "2024-02-20", status: "confirmed" },
];

export type UserRole = "seeker" | "company" | "admin";
